# Generated by Django 5.1.1 on 2024-09-20 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="MuscleGroups",
            new_name="muscle_groups",
        ),
    ]
